spring:
  application:
    name: demo-mybatis-plus

  # Mysql ?????
  datasource:
    url: jdbc:mysql://localhost:3306/demobatis?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1qaz1qaz
    driver-class-name: com.mysql.cj.jdbc.Driver